repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
    -   id: shellcheck
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-frontmatter
      - mdformat-footnote
